### ISSUE TITLE
Adopt FreeBSD's pkgng

### ISSUE THREAD

**Issue by yonas** [bitrig/bitrig-ports#72] opened 2015-10-18 05:47 UTC
> The current plan is to keep the OpenBSD ports tree, however, this plan may change in the near future.

It would be great if bitrig adopted FreeBSD's pkgng package manager. Having a single `pkg` command for everything I need is awesome. Also, I should be able to just `pkg install some-package` on a new install without fiddling with `export PKG_PATH=...`, like with FreeBSD.

**Comment by jcvernaleo** [comment] 2015-10-18 11:53
I believe PKG_PATH should be set by default to the current snapshot.  If it is not, they we should fix that.

Other than that, I'm not too familiar with FreeBSD's package manager.  Most of the Bitrig devs are more familiar with OpenBSD's packages so from my perspective anyway it would be a lot of effort with seemingly little return.

Of course if you want to start the work I'm sure there are people who would help and I'd give any advice that I could.

**Comment by yonas** [comment] 2015-10-19 06:39
Thanks, I created a new issue for PKG_PATH: https://github.com/bitrig/bitrig/issues/69

**Comment by drahn** [comment] 2015-10-19 11:12
There was a bug in the latest snap that /etc/pkg.conf was not created, this bug was fixed but the snap was not rerolled. That file contains the static PKG_PATH setting.


- Dale



-------- Original message --------

**Comment by yonas** [comment] 2015-10-19 11:28
@drahn Thanks Dale!

**Comment by yonas** [comment] 2015-10-19 11:39
I've managed to build pkgng on BitRig. It seems to run fine. Here you can see FreeBSD packages:

```
-bash-4.3# pkg update -f
Updating BitRig repository catalogue...
Fetching meta.txz: 100%     944B   0.9kB/s    00:01    
Fetching packagesite.txz: 100%     5.2M   1.8MB/s    00:03    
Processing entries: 100%
BitRig repository update completed. 24515 packages processed.
```
```
-bash-4.3# pkg search bash
bash-4.3.42                    The GNU Project's Bourne Again SHell
bash-completion-2.1_5,1        Programmable completion library for Bash
bash-static-4.3.42             The GNU Project's Bourne Again SHell
bashc-3.2.33.0_1               GNU bash shell extended with visual two-panel file browser
checkbashisms-2.15.5           Debian script that checks for bash-isms
erlang-mochiweb-basho-2.9.0p1_1 Erlang library for building lightweight HTTP servers (Basho fork)
p5-Bash-Completion-0.008_1     Extensible system to provide bash completion
p5-Term-Bash-Completion-Generator-0.02.8 Generate bash completion scripts
ru-fortune-bashorgru-20080903_1 Fortunes from bash.org.ru and freebsd.rusnet.org.ru/bash
```

Now to get the backend repository setup. I'm not sure how pkgng packages describes package dependencies.

**Comment by jcvernaleo** [comment] 2015-10-19 13:43
Unfortunately, the issue is never really the package manager but the packages behind it.  Enough of them generally need local patches or other little hacks to work that using a separate source of packages can be a ton of work.  That's why I'm not particularly interested in duplicating efforts across multiple package managers when ports works pretty well.

**Comment by jcvernaleo** [comment] 2015-12-08 16:02
@yonas Since we don't plan on adopting pkgng completely I'm closing this issue.

I'm totally happy allowing it as an alternative or just making sure it works with bitrig.  So if there is anything you need from us for either of those two goals, please open another issue and I'll take care of it as soon as I can.

Thanks!

**Closed by jcvernaleo** 2015-12-08 16:02 UTC

**Comment by yonas** [comment] 2015-12-09 21:03
@jcvernaleo Thanks for your support. I've upstreamed my patches to pkgng, so the standard pkgng should compile on OpenBSD/BitRig.

I've also written a script that converts OpenBSD/BitRig packages into the pkgng format: 

https://github.com/yonas/pkg-convert

I was thinking of writing a pkgng plugin that uses the pkg-convert script to fetch packages from OpenBSD/BitRig and automatically convert them. If anyone's interested in helping with that, please let me know.
